definitions:
  model.User:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      fullname:
        type: string
      id:
        type: integer
      last_login:
        type: string
      updated_at:
        type: string
      user:
        type: string
    required:
    - id
    type: object
host: localhost:8001
info:
  contact: {}
  description: This api for demo app
  title: Grand-Demo-API
  version: "1.0"
paths:
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: UserID
        format: int
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.User'
      summary: Create User
      tags:
      - User
swagger: "2.0"
